version: '3.8'
services:
  es:
    build:
      context: .
      args:
        ELK_VERSION: 7.17.8
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.8
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - elastic

  redis:
    image: redis:7.0.7
    command: redis-server --port 6379
    container_name: redis
    hostname: localhost
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    depends_on:
      - kibana
    networks:
      - elastic

  app:
    container_name: spring-bookstore
    image: openjdk:11-jdk
    ports:
      - 8080:8080
    volumes:
      - ./build/libs:/app
    working_dir: /app
    command: "java -jar bookstore-0.0.1-SNAPSHOT.jar"
    depends_on:
      - redis
    restart: always
    env_file:
      - .env
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
