Spring:
  datasource:
    url: jdbc:mariadb://springboot-bookstore.cax1ze4epfd5.ap-northeast-2.rds.amazonaws.com:3306/bookstore
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(kZulKeTBTgwhJQAnuZ3plG4LXV6ciAfE)
    password: ENC(t7APcxR4FMdHo/DbY+BEPdAPiIKnyUGz)

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: redis
    port: 6379

elasticsearch:
  host: es
  port: 9200

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

jwt:
  token:
    secret-key: ENC(2d8GK4NebTSu0JbuLHwNbPicu4B4jigJ)
